### PR TITLE
Global Bans

### PR DESCRIPTION
**Pull request by Yushe**
I tested them and they work perfectly.

Also fixed the ban page a bit e1b96af

### CODE REVIEW

**Comment by Yushe** [comment]
Making a post will not redirect you to banned.php and it will create the post. (major issue)
This probable doesn't have anything to do with the global bans table.

**Comment by RePod** [comment]
It's a configuration file for a reason, therefore its defaults are already tentative.

The option you changed specifically is intended to be automated for casual usage and results in each board having their own bans table. This gives the users the option to, like you did, make that small change to share tables and their contents (and it's under the "Advanced" section).

This modification is more suited to be on the [Wiki](https://github.com/spootTheLousy/saguaro/wiki) (somewhere) explaining if people just want a single global ban table this is how to do it.

However, finding that malformed HTML tag is nice.

@Apogate can chime in on this, but I reject this change.

**Comment by Yushe** [comment]
I feel like it should be added because it will make it easier for people to manage there site running saguaro.

**Comment by RePod** [comment]
It's clearly a simple change, looking at your commit: you just removed the _PREFIX_.

It'd be easier to instruct users on how to do this (removing _PREFIX_ instead of adding it back) if they want to share ban tables. Again, more suited for the [Wiki](https://github.com/spootTheLousy/saguaro/wiki).

**Comment by Apogate** [comment]
Seeing the confusion, for future users it would probably be worth writing something in the config comment about removing `PREFIX` to allow global tables.

As it stands, I don't think this needs to be merged.

@Yushe Instead, if you'd like to edit the config line comment to explain this+link to the wiki but revert the line back to `define(SQLBANLOG, PREFIX . "_mod");`, that'd be worth merging.

Good catch with **banned.php**.

**Comment by Yushe** [comment]
The wiki page just need to be changed now.

**Comment by RePod** [comment]
A new PR would be better to avoid spamming commits (that revert themselves).

**Comment by Apogate** [comment]
I'll be screaming about regex and deleting a lot of shit while I try to get the quote fixes done, if you want to wait yushe, it would prevent git conflicts

**Pull request closed without merging**
