### PR TITLE
Rewrite Upload Check

### PR DESCRIPTION
**Pull request by RePod**
Mostly broken as of merging #220, due to relocating file information and proper handling of error cleanup.

**_SOON**_

### CODE REVIEW

**Comment by RePod** [comment]
@Apogate 

> might be better to add another `host` column to the media table
> i know i wanted to add a resto column to it as well for deletion purposes

The `host` column can be obtained via reverse-lookup from the media table to the post table, since each file has an associated `parent` column which is the post number.

~~The latter is the same, to know the `resto` you'd reverse-lookup the `parent` to know.~~ But I did it anyway.

It's an extra step but it keeps the post and file information separate from each other.
Fortunately, you can get both in a single go.

~~Interestingly, I just noticed a case in the upload check where having the `resto` would be useful (the media check).~~ **DONE.**

**Comment by RePod** [comment]
Awaiting @Apogate DreamDestroyingReview:tm: and feedback on how much we need a `host` column for files (despite not being associated with them, see above).

`resto` was added and acts as expected. (0 if OP, otherwise target OP) (breaks day-old legacy :+1:)

The cooldown check is a little flaky, but we were fine with it before (and if anything it's gotten _slightly_ better). I've observed instances where double posting is possible but don't know the cause or if it's still a thing.

**Comment by Apogate** [comment]
Host column would be handy for duplicate file checks, old regist used it to check people spamming the same file. Still think it wouldn't hurt just to have it.

**Comment by Apogate** [comment]
Also looks good to merge, I'll leave that to you

**Comment by RePod** [comment]
> Host column would be handy for duplicate file checks, old regist used it to check people spamming the same file. Still think it wouldn't hurt just to have it.

Seems like something intensive enough to be considered a special case. If it got that far wouldn't it be fine to lookup the files' host on the post table separately then?

For instance you'll never see such a feature outside of moderation (except for blacklisted hashes which wouldn't matter) so when it is required:
- Fetch file info
- Reverse-lookup to post table to get more/post info (including host)
- etc

The whole point of a dedicated post and file table is to only deal with their info. When combined they'd provide a lot (everything about a post), but can be managed easier to get specific information cleaner and faster from a dedicated location. In no way is an actual file attached to an IP/host, but a file is attached to a post which is attached to an IP/host.

Similar to how our classes are working, the hierarchy can be thought of as:

> IP/host <- (owns) post <- (owns) files

**Comment by RePod** [comment]
Wrap this up as you see fit and merge.

I recommend taking out the entire MD5/hash check in _regist/regist.php_ since it was updated and relocated to check per-file.

**Comment by Apogate** [comment]
Looks good, don't want the headaches associated with touching the upload check while that potential merge conflict is still there. I'll remove it in a bit.

**Pull request merged**
