### PR TITLE
Multiple file uploads.

### PR DESCRIPTION
**Pull request by RePod**
- [Current Testing ZIP](https://github.com/spootTheLousy/saguaro/archive/file-table.zip)
  - Newer, working admin. (eventually)
- [Pre-Merge Testing ZIP](https://github.com/spootTheLousy/saguaro/archive/ad2dfeb018198b9efc79a0ffe88b848e0b556a4c.zip)
  - Old, semi-working admin.

---

~~Never~~ Kinda safe to merge.
- _SQLMEDIA_ added as new config define.
- _test.php_ generates the new table, and once again legacy is broken due to removing columns from _SQLLOG_.
  - Probably the most ham-handed legacy defiling change, as it actually deals with the data.
    - Theoretically possible to maintain legacy support by moving and renaming things as usual, but I don't want to do it.
    - While on-the-fly legacy support could be added (if no media column, work like old), it then becomes a time bomb of "how long do we keep this?"
  - Up there with the rewritten Regist.
- _SQLLOG_ now had a new `media` column, which contains a space-delimited list of rows to lookup.
  - Probably done the worst way possible, and will trigger somebody.
- Accepts multiple files via upload at once.
  - Processed individually as intended, with unique thumbnailing.
- Rewrote image thumbnailing.
  - Fixed saving PNG and GIF thumbnails as PNG to preserve transparency.
- Front-end support, ~~at least for the first file.~~ Currently just spits it all out.
  - Fixed hard-coded `.jpg` thumbnails to reflect above fix.
- File names and thumbnail names are now `TIM-#.ext`.
  - Instead of `1234.jpg`, `1234-1.jpg`. Even if only one file.
  - If multiple files, numbered accordingly: `1234-1.jpg`, `1234-2.webm`, `1234-3.gif`, etc.

**TO-DO**
- [x] Relocate/write upload file _processing checks_ to check each file.
  - Return-early to skip them.
- [ ] Fix Catalog thumbs if broken.
  - May your god help you.
- [x] Re-enable duplicate hash check.
  - _Not_ de-duplicating, for now.

**@Apogate's TO-DO**
- [x] Max file limit. `Regist->extractFiles()`
  - If undefined, default to 1.
- [ ] Handle multiple files everywhere else, specifically deleting.
- [ ] Make it look good.

Unfortunately, since the actual image HTML generation is so bad I made a "relatively huge" compatibility fix in _post.php_ to give it the information it needs to not explode.

---

Caveats:
- Uses HTML _5?_'s file select attribute of `multiple` or `multiple='multiple'` to allow multiple files to be selected.
  - Don't know how this degrades, probably fine.
  - However, anything that simulates multiple file select boxes would work (including adding them manually).
- Additional SQL table purely for files, and no organized or simple way of looking up.
  - Currently blindly reverse-looks up based on the intended parent number, instead of parent's media column.
  - Either way, we'd have to cross the streams.

---

**What is reverse-lookup?** Take the known post number, and pull row/s from the file table where the `parent` column has a value of that.

### CODE REVIEW

**Comment by RePod** [comment]
It's functional for the most part, except a few inconsistencies.
You'd be hard pressed to see the difference if only using one file.

@Apogate can now start on the to-do list in the main post.

**Comment by RePod** [comment]
@Yushe if you decide to test this, know using old boards is _really_ difficult if not near impossible without very specific instructions.

**Comment by Apogate** [comment]
I'm still pushing for [Dropzone](http://www.dropzonejs.com/#installation) (MIT license) as it has no dependencies, looks pretty lightweight (only one 62Kb file), can be included in the plugins folder and only requires one line in `postform.php` to enable it. If the library isn't found, it would default to the current file selector.

It has a lot of [useful options](http://www.dropzonejs.com/#configuration) that provide a lot of client-side checks such as file size, type, filename sanitation etc. Would be easy to replicate next's client md5 checking down the road if we ever wanted to. Added bonus of cross-platform familiarity for users coming from lynxchan, infinity or infinity next, since those engines use it too.

**Comment by RePod** [comment]
For what it's worth, you can still drag+drop with this native implementation.

I wouldn't mind adding support for it, but no reason to include it in the repo itself.

I'm also considering moving the dynamic SQL generation to the _SaguaroQL_ class (the parent one) so everything can use it, don't know if it's good for this PR though.

**Comment by Apogate** [comment]
> I'm also considering moving the dynamic SQL generation to the SaguaroQL class (the parent one) so everything can use it, don't know if it's good for this PR though.

We can do that in another pull after this one is merged, since we'll have to address using bound/prepared statements for increased security down the road. Looks like we have another #64 on the horizon. :skull: :skull:

**Comment by RePod** [comment]
All the `float` CSS involved makes it particularly difficult to relocate these properly, don't have an idea to solve that.

**Comment by RePod** [comment]
The purpose for the majority of these last few commits was to raise error-handling a little closer to the surface. The Image/Video processors don't need to be throwing errors, just processing them and chiming in when a reasonable problem is found.

Currently this is done by a stream of objects with a `passCheck` (bool) and `message` (string) property. `message` is used to contain the error, which is basically the only time a processor would have something to say. The parent it returns its results to handles `passCheck` accordingly, and if we want to inform the user we can use `message`.

**Comment by RePod** [comment]
Ded pull request.

At the very least, configure/stabalize it for single file uploading and unleash this terror on the world.

**Comment by RePod** [comment]
Before merging, remove the actual _dropzone.js_.

**Comment by RePod** [comment]
Are we there yet?

**Comment by RePod** [comment]
Any ideas on how to handle what the Catalog shows?

I can't think of any way to show potentially infinite files uniformly other than some sort of mini slideshow with JS (which isn't a good idea). This leaves me with the only sensible option: just the "first" file, but that's misleading.

Counting the number of media files in the thread may be intensive too.

**Comment by Apogate** [comment]
I'm holding off on anything catalog related as I am gearing up to render it entirely in json based on our new catalog.json. Puts the entirety of the processing for the catalog on the client, one less page we have to rebuild constantly too. 
We can add a `file_count=(int)` value for each OP in the API?

We can set it so Saguaro will always output catalog.json in the board root regardless of the `ENABLE_API` setting. Toggling the api off/on from the config could just turn individual thread json creation on/off instead?

**Comment by RePod** [comment]
API is backseat to improving the back end, hard to determine gains upfront before bigger changes like this settle.

**Comment by RePod** [comment]
**_Soon.**_

**Comment by Apogate** [comment]
DELETE THIS

**Comment by RePod** [comment]
I just had the delightful experience of seeing how another imageboard software rendered multi-file posts and through sheer luck while I was making my initial support (to have them at all) I achieved a similar result.

However, it looks like complete garbage and there has to be a better way.

**Comment by RePod** [comment]
Yolomerge soon. Shouldn't take 3 months to reach a consensus.

There's a few problems throughout the repo currently that this fixes, and some that need to be fixed afterwards that aren't within the scope of this PR.

The main "issue" with this PR is the scaling introduced by yet another table in the database. There's no clean way around it (especially keeping posts and files together) but it also provides more flexibility moving forward. However, in doing so _all_ the framework required for multiple files of any supported type is **done** and not a problem (apparent now with multi-file posts including images and webms).

Most performance overhead is negligible if it functions similar to a single file installation, which if not already will be configurable.

This PR also improved Regist's security quite a bit (fixing my previous mistakes during the great rewrite) by manipulating temporary files properly instead of moving them and handling them in errors, among other things. A few additional steps in and out of Regist were also rewritten, like thumbnailing and HTML generation, to ease with the process.

There's no reason to keep this hanging out to dry.
~~At most, this is missing duplicate hash checking and removing Dropzone (but not support) before being 100% ready to go.~~ **DONE**

**Comment by RePod** [comment]
Admin features (delete, moderate, prune) need to reflect the changes of this PR.
I don't mind handling it myself, though.

``` PHP
//Reverse lookup from the media table based on predetermined parent number. (BEST-ish)
$no = 1;
$query = "SELECT localname,localthumbname FROM " . SQLMEDIA . " WHERE parent='$no'";
//Returns file name in src and thumb (or equivalent) directories for each.

//Regular lookup from log table. (MEH)
$no = 1;
$query = "SELECT media FROM " . SQLLOG. " WHERE no='$no'";
//Returns space-separated string of respective SQLMEDIA table "no" column values.
```

When done, would have to update the parent's media column. This can be done manually by adding/removing what is required on-time or automatically by checking the media table again.

The former:
- Read from SQLLOG to get current media column value
- Cache and manipulate manually
  - More prone to error
- Write back

The latter:
- Read from SQLMEDIA:
  - `"SELECT no FROM " . SQLMEDIA . " WHERE parent='$no'"`
- Returns similar/less information (simply the _no_ column value)
- Minimal caching and no manipulation needed (combine into string with spaces)
- Write back

Most of the changes should just be determining the targets and updating with the results.
The file table should have all information required for admin features.

I'd recommend getting the media column, counting the number of items it has (explode by spaces), and stating "1 file", "2 files", etc. to avoid needing to lookup from the top level of the deletion page. The dedicated, extended info page can handle actually looking up the files and presenting them.

I'm also now considering removing the media column or changing it just to reflect the number of media files it has directly (instead of listing their _no_s), since reverse lookup (look at media table by parent) is always going to be better. Just counting them would make more sense, as you pull the info from the _post_ and learn how may files it has but nothing about them.

---

After initial checks, a majority of the admin area is broken due to using `list()` to extract query columns into the scope. `list()` is 1:1 with its arguments and therefore "hardcoded" to the order or existence of columns it receives. Fortunately, this is the largest problem so after that is dealt with the rest is minor stuff (the multiple files).

Instead of using `list()`:
- Fetch the result with `fetch_assoc()`
- Cache the result and access properties via `$result['column']`

The current problem with admin code:

``` PHP
$result = ['Ecks', 'Dee', 'Lmao']; //Returned array via $mysql->fetch_row().
list($col1,$col2,$col3) = $result; //Extract all three items to respective variables.

$result = ['Ecks', 'Lmao']; //'Dee' was removed, so the third column became the second.
list($col1,$col2,$col3) = $result; //$col2 is now $col3. $col3 does not exist or is undefined.

//Solution:
$result = $mysql->fetch_assoc("insert query here");
$col1 = $result['firstColumnName']; //Quick and dirty fix.
echo $col1;
echo $result['firstColumnName']; //Recommended.
```

Easy, @Apogate.

**Comment by RePod** [comment]
@Apogate I caught this up with master if you want to work with the current changes, although there were little conflicts (except __core/page/head.php_). You should re-fork instead of syncing to avoid another merge commit, but it's not required.

Log was auto-merged and should be reviewed. (seems fine after testing the merge)

**Comment by RePod** [comment]
I'm gonna do it.

**Comment by RePod** [comment]
__core/regist/process/upload.php_ needs to be updated to determine cooldowns for media posts.

This can be done by either reverse-lookup on the file table, or checking the `media` column on the post table (meh).

Not my area of expertise since we're still debating on how to use the `media` column.

**Comment by Apogate** [comment]
k.....keep me posted

**Comment by RePod** [comment]
Problems for future generations: (our children) (post-merge checklist)
- [ ] Duplicate hash check on upload before writing to avoid dupes in the post itself?
  - Can already do this now, but lazy.
- [ ] Actually handling multi-file everywhere else
- [ ] Media file cooldown check
  - __core/regist/process/upload.php_
    - More specifically this ENTIRE file since it relied on cleaning up itself if there was a problem, which is no longer the case.
- [ ] Fix 99% of the Javascript
- [ ] Make it look good

**Pull request merged**
