### PR TITLE
Bans - The return

### PR DESCRIPTION
**Pull request by Apogate**
The aim of this PR is to optimize, rewrite and add functionality to saguaro's ban suite. 
## Checklist:
- [x]  **Under the hood:**
  - [x] Cleaning up **admin.php** removing `extract()` dependency
  - [x] `isBanned()` has redirect to **banned.php** flag option.
  - [x] Optimize/rewrite **banned.php**
    - [x]  Since ban class is initiated in **banned.php** anyway, might be better to have all the checks done in the class, with banned.php just acting as the client end "portal". 
- [ ] **New features:**
  - [x] `autoBan()` function. _Unimplemented right now, might hook into a blacklist later.._ 5832c8f
  - [x] Banned page shows what post ban was filed for 5832c8f
  - [ ] Rangebans
  - [ ] Appeals for bans of certain length. Maybe customizable minimum appeal length. Smells like ~~more config options~~ teen spirit.
- [ ] **Panel - Bans:**
  - [ ] Ban search from panel
  - [ ] Appeal management
- [x] **Redesign:**
  - [x] Banned.php CSS
    - [x] Sagurichan support for WS boards
    - [x] Saguaba support

<hr>

More to come. Ban suite has always been a patchwork of code running on prayer and glue. maybe that will change.

### CODE REVIEW

**Comment by RePod** [comment]
Eventually implement captcha for user ban checking, similar to 4ch, to rate limit/stop automation.
Basically protect the SQL read with a captcha.

**Comment by Apogate** [comment]
[Meme redacted] - RePod police

**Comment by Apogate** [comment]
I CHANGED MY MIND

**Comment by Apogate** [comment]
behold the future

image

We've come so far
image

**Comment by Apogate** [comment]
THE FUTURE IS NOW

image

**Comment by Apogate** [comment]
Eh. We'll leave appeal handling up to the site owner for now. Inline appeals are low priority.

Ready for merging

**Comment by RePod** [comment]
- Captcha?
- Hopefully uses the Page class.

**Comment by Yushe** [comment]
@Apogate test.php appears blank when you access it, and yes I have checked there is no lockout file.

**Comment by Apogate** [comment]
Open test.php to edit and search for the SQLBANNOTES LINE. it needs a comma at the end of the line, I was going to push a fix tomorrow morning

there is also a bracket missing at the end of core/admin/delete.php for the deleteUploadedFile

unfortunately i cannot push a fix for this until later tonight, so you can either fix it yourself or wait until later

**Comment by Apogate** [comment]
alternatively just delete the whole damn line, the query doesn't work anyway

**Comment by RePod** [comment]
Worth noting you didn't sync with master before merging so a lot of things were reverted (like the readme) albeit partially. Previously, I removed mention of FFmpeg from the readme and now it's back.

>Side effects of not waiting for dream destroying review.

**Comment by Apogate** [comment]
looks like i have a revert in my future

**Comment by RePod** [comment]
Also nuked the licenses in my jQuery files, just another example.

Too bad it's going to be hard to revert the repo since commits have happened since then.
I think the problem was caused by your original sync with master but you may not have done the same on your server, so they came back.

**Comment by Yushe** [comment]
ipnotes table is failing to create (1064)

**Comment by RePod** [comment]
_test.php_ has links at the bottom for SQL error codes (and what they mean).
:rainbow::star2: _The more you know!_

**Comment by Apogate** [comment]
@RePod manually re-added missing commits, I think i got everything.

@Yushe ~~everything is now fixed &~~ added some dumb features as well. your google-fu is weak young one. good luck

test.php is still broken for some unholy reason. even with the error. off to stackexchange i go

**Comment by RePod** [comment]
is there a reason you didn't just expand the existing ban table?
Other than maintaining legacy support?

**Comment by Apogate** [comment]
If a user wants to have a ban table for a specific board, but have a global log of all bans, it's much more useful to set it up independently from the ban table. Legacy support was just an additional perk.

**Pull request merged**
