### PR TITLE
Fix quotes

### PR DESCRIPTION
**Pull request by Apogate**
R-right guys? Shouldn't be a security issue.

### CODE REVIEW

**Comment by RePod** [comment]
Hard to tell.

I only know my text processors prefer &gt; which may have been the cause.

**Comment by Apogate** [comment]
With some testing, the processor seems indifferent to `&gt;` or `>`

**Comment by RePod** [comment]
`&gt;` I mean.

**Comment by Apogate** [comment]
Shuffled greentext into the autolink class so formatting less spread out between files. 

I know `greentext.php` is a thing, eventually we'll shift over to that I presume?

**Comment by RePod** [comment]
Yes that's fine.

**Comment by Apogate** [comment]
Hot. Merged

**Comment by Apogate** [comment]
Hot. Merged.

**Pull request merged**
