### PR TITLE
Noko, sage, stickies, locking and bug squashing

### PR DESCRIPTION
**Pull request by ghost**
==Saguaro build 0.99.00==
+Fixed a bug where a user deleting OP posts with replies does not remove the replies from the manager log
+Added functional noko
+Added nokosage, so you can noko while you sage
+Manager posts now have the option to post a sticky or locked thread. Threads cannot be retroactively stickied or locked (yet).
+The post date display is now customizable in config.php, default is american month/day/year formatting.
+Backend has been set up for later manager ability to silently permasage threads, retroactively sticky and lock

Known bugs: 
-If the previous post number in the log has been deleted, users trying to start threads using noko will be directed to the oldest OP post in the log (uncommon, medium priority bug)

****_UPDATING FROM PREVIOUS VERSIONS**_***
Delete your index.html, access your main php script (imgboard.php) to rebuild the board. using the update button will not work.
EDIT: All you have to do is manually enter the new sticky, permasage, and locked columns (in the right positions) using phpMyAdmin or something similar

This build has ACTUALLY been tested and is ready for merge, if any bugs are found please let me know.

0.99.00 - This build
    +Features noko, nokosage, manager post sticky/locking and bug fixes
0.99.25 - Planned build
    +User managing, login based administration backend

### CODE REVIEW

**Comment by ghost** [comment]
i went to all this trouble to bake this nice cake any nobody notices

**Comment by RePod** [comment]
Here's a quick bug and fix you could implement along with this:
If the config is unable to load, the language cannot be loaded. This makes it hard to debug early steps (such as failed SQL connections)

`
include "lang/" . LANGUAGE . ".php"; //Language file.
`

to: (untested)

`
include "lang/" . (LANGUAGE) ? LANGUAGE : "en-us" . ".php"; //Language file.
`

If LANGUAGE is defined in time, use it. Else fallback to "en-us".

**Comment by ghost** [comment]
You reminded me that I had meant to push a debug mode too, I added the language fix to the pr.

**Comment by RePod** [comment]
As noted in the reference, #9 cannot be merged until your changes are as it requires a change to imgboard.php.

If you commit [the suggested change](//github.com/spootTheLousy/saguaro/pull/9#issuecomment-102869474) it would save me the trouble.

**Comment by ghost** [comment]
This is ready to merge. I'm not going to add anything further to this pull

**Pull request merged**
