### PR TITLE
Catalog is now useable

### PR DESCRIPTION
**Pull request by Yushe**
Simple fix.

### CODE REVIEW

**Comment by RePod** [comment]
Aside from the fact it wasn't ready for any production environment status before, this change doesn't accomplish much.

It was done that way by default due to [.htaccess](https://github.com/spootTheLousy/saguaro/blob/master/.htaccess_sample#L7)/mod_rewrite rewriting the URLs transparently. For your change, simply uncommenting _PHP_EXT_ would have been better (and less hard-coded since it could potentially not be `.html`).

For example, if Catalog linked `/board/res/1`, .htaccess/mod_rewrite would transparently (without the user knowing any better) load `/board/res/1.html` for a cleaner looking URL. This may also have led you to believe that Catalog "was broken". It wasn't, your testing environment was not accurate.

**Comment by Apogate** [comment]
Wait, what does this PR fix?

Saguaro's /<a href='http://boards.saguaro.tk/bta/catalog' target='_blank'>bta</a>/ board is running our most recent release branch, and the catalog works fine :?

**Comment by RePod** [comment]
Looking at /bta/'s example you can see (even in the current URL being just `/catalog`) the URLs themselves appear fine. .htaccess is doing all the work server-side. The only thing broken is the jQuery suite because of similarities with legacy elements and formatting, whenever I work on those again that'll be fixed (or we could not load them, I don't know).

It would be more beneficial to determine if there's a rewriting rule (which isn't particularly easy) for these URLs and have Catalog format the links accordingly.

**Comment by Yushe** [comment]
It doesn't work fine on my website for some reason.

**Comment by Apogate** [comment]
> He who knows when he updated and when he did not, will be victorious.

sun tzu said that. and he was the greatest imageboard developer of all time.

ll give you a checklist and let us know if you still have problems.
- update imgboard.php 
- update .htaccess_sample
- rename .htaccess_sample to .htaccess (url rewriting wont work if you do this)
- update all **_core/catalog/**\* folder contents

I visited your <a href='http://3chan.ml/3' target='_blank'>test board, /3/</a>.

<a href='http://3chan.ml/3/imgboard.php?mode=catalog' target='_blank'>Your catalog works</a>, it just looks like you haven't renamed .htaccess, which is why visiting _3chan.ml/3/catalog_ doesnt work. .htaccess is what handles the "redirection" there.

Also like RePod said, the jquery suite has to be updated to accommodate the new HTML and features, which I'm trying to work on. 

I'm going to reference this issue in the wiki because this will probably be a recurring issue for users who don't know how url rewriting works

**Comment by Yushe** [comment]
I thought .htaccess not being renamed might be the problem.

**Comment by Apogate** [comment]
case closed

**Pull request closed without merging**
