### PR TITLE
Refactoring and formatting changes.

### PR DESCRIPTION
**Pull request by ghost**
- Rewrote the whole script in a prettier (read:actual) formatting style
- Moved jquery & captcha to 'plugins' folder, edited appropriate
  locations in imgboard.php
- Minor tweaks to readme to explain the usage for gif2png and added
  actual PHP/MySQL version requirements
- replaced opening <? with <?php to remove potential conflicts for users
  whose server configurations might not have short tags enabled.

+defined PLUG_PATH in config= relative plugins folder file path

-ily spoot

### CODE REVIEW

**Comment by RePod** [comment]
> Rewrote the whole script in a prettier (read:actual) formatting style

You dedicated man. :(

> replaced opening <? with <?php to remove potential conflicts for users whose server configurations might not have short tags enabled.

This was a long time coming and the biggest issue when I set up a local test server. I went easy route and just enabled short tags in my PHP config.

Give me a year to look over the _imgboard.php_ changes. I've been telling spoot for years to make it modular, this might be a good first step.

Is it safe to assume most of the deletions were just relocated?

**Comment by ghost** [comment]
Nothing was changed functionality-wise, just formatting so far. Give me some time and the actual feature updates will start rollin' out.

**Comment by spootTheLousy** [comment]
Wow, this is a whole lot. When you said contribute I expected a small feature or something to that effect.
While I play around with this and see what all is in this bundle of wonder, I'd like to invite you to the IRC channel for a speedier chat sometime.

**Comment by RePod** [comment]
> Rewrote the whole script in a prettier (read:actual) formatting style
> 
> You dedicated man. :(

In retrospect, we probably should have reconsidered this.

**Comment by Apogate** [comment]
how so

**Comment by RePod** [comment]
A million spaces.

**Comment by Apogate** [comment]
past apogate did nothing wrong

**Comment by RePod** [comment]
At least we have a label for it.

**Pull request merged**
