### PR TITLE
Panel redesign - Functional

### PR DESCRIPTION
**Pull request by Apogate**
Part one of two:

This push does a LOT of stuff so I'll try to keep it pretty.
- Adds new features to the panel such as
- Search for posts by number or IP
- a "Delete all by this IP" button for spammers/raids
- Ban panel is no longer in the "Post Info" button, but instead is
  available via a popup right in the deletion list
- Advanced sorting options such as:
- Show OPS only in post list
- Show a thread + replies only in post list
- Show all posts by specific IP in post list (This one is neat as it can
  be done without revealing the IP to the admin, so this feature wouldn't
  have to be restricted to just moderator+)
- Slight redesign with the intent of reducing the number of clicks
  needed to carry out actions.
- Double click comments in the panel to view the full comment

Functional changes:
- I'm attempting to reintroduce language file support. From here on out,
  all commits by me will be done using language strings again. I will not
  support any langauge files other than english, however. USA USA
- Optimized admin.php, rewrote the entire switch statement to try to
  make it less of a clusterfuck. @RePod I bet i can make admin.php smaller
  than imgboard :^)
- Renamed my stupid filenames/classes for improved readability

Future plans:
- A panel-specific stylesheet which will greatly help with readability
  and make this much nicer looking

Issues that need to be resolved before this can be merged:
- You can't delete anything from the panel right now. lmoa

### CODE REVIEW

**Comment by Apogate** [comment]
This PR also adds opportunity for expansion:

You can hop right to posts in panel view from anywhere now by visiting **[board url]/admin.php?mode=res&no=[post#]**, as well as submit bans via a url **[board url]/admin?mode=ban&no=[post # to ban]**

both which would make implementing anything in a javascript/jquery admin extension much easier.

**Comment by Apogate** [comment]
Fixes #174

**Comment by Apogate** [comment]
Fixes #170

**Comment by Yushe** [comment]
So does this or the latest commits fix the br bug? Because my users are getting really annoyed at me for not implanting a fix.

**Comment by RePod** [comment]
Then implement one, you can contribute too.

**Comment by Apogate** [comment]
@Yushe i'll give you an amswer when you upload your core folder code for /v/ :^)

**Comment by Yushe** [comment]
@Apogate I have uploaded it https://github.com/Yushe/3ch/issues/1

**Comment by Apogate** [comment]
@Yushe 
Yes - To update for this one however, you're going to have to delete **/plugins**, **/css** and **/core**
and replace them

You'll also have to replace imgboard.php and admin.php

**Comment by Yushe** [comment]
@Apogate I always replace those files.

**Pull request merged**
