### PR TITLE
Convert saguaro ql

### PR DESCRIPTION
**Pull request by Apogate**

### CODE REVIEW

**Comment by RePod** [comment]
Are you finished with those errands? Or are you waiting on review?
If you need certain things implemented, I also need to know.

I got another large-scale change that needs to be done after this.
Starts with _every_ ends with _thing_.

**Comment by RePod** [comment]
If anything does not work, instead of reverting check the code and fix it.

We'll focus on MySQL first, and once everything is converted over properly we can swap to MySQLi.

**Comment by RePod** [comment]
These files are the only ones left using `mysql_*`, specifically `mysql_result()` with 3 arguments:
- _Admin/validate.php_
- _Regist/process/upload_file.php_
- _Regist/Regist.php_

So far I haven't noticed anything broken.

**Comment by RePod** [comment]
MySQLi has no complement(...) for the already shaky `mysql_result()`.

Basically, the MySQLi instance of SaguaroQL cannot accurately replicate it and is currently using backwards-compatible code returning the expected result.

As such, after this pull is cleared usage of `mysql_result()` should be removed in favor of something better.

**Comment by RePod** [comment]
For the purpose of this PR, everything is done. All instances of MySQL interfacing have been replaced to use the SaguaroQL class.

I didn't test it thoroughly for bugs, but I honestly can't expect any (that didn't already exist).

After this is confirmed working we can start working towards MySQLi.

_imgboard.php_ is now less than 90 lines.

**Comment by Yushe** [comment]
You know I'll test it loads and report all the bugs I have found when it is done.

**Comment by RePod** [comment]
- Can't login.
- Posting isn't generating pages.
  - And redirecting to res/0.html.

**Comment by RePod** [comment]
SaguaroQL's MySQL and  MySQLi now have better type handling.

Before, some of the functions, such as the `fetch_*` ones, were being passed a _resource_ which was being piped directly into a query to be ran as normal which is not correct.

The classes now detect and support both _resources_ and _query strings_. Using _query strings_ is preferred however as it skips a step by automatically running the query and processing _that resource_ as intended.

For example, these two blocks do the same thing:

``` PHP
$result = $mysql->query("something");
$blah = $mysql->fetch_row($result);
```

``` PHP
$blah = $mysql->fetch_row("something");
```

Legacy code will now function as normal again, but in the future converting things (such as the _Admin/validate_ fix above) to the latter example would greatly improve readability.

~~I think with THESE fixes, this is more suitable for bug testing and 99% accurate.~~

**Comment by RePod** [comment]
Ur 2 slo

**Pull request merged**
