### PR TITLE
Make regist slightly more organized

### PR DESCRIPTION
**Pull request by Apogate**
Slight tweak to file structure, makes finding regist immediate in the
regist folder. All regist subordinate files have been moved to
_core/regist/inc/*

### CODE REVIEW

**Comment by Apogate** [comment]
and there it is. the conflict

**Comment by Apogate** [comment]
Wew conflict resolved i am the greatest

**Comment by RePod** [comment]
Arbitrary hierarchy but if it works I don't really care.

**Comment by Apogate** [comment]
go team

**Comment by RePod** [comment]
Just now there's a disparity between this having an inc folder and everything else not

**Pull request merged**
