### PR TITLE
Admin revisions

### PR DESCRIPTION
**Pull request by Apogate**
Flaming wreck edition

Adds:
- Ban requests for janitors
- Cleaned up style on ban form for moderators.
- Broke both bans and reports down to minimize memory usage.
- Beginning to port admin.php into imgboard.php.

major changes: entire report queue backend has been rewritten.
Eventually, the entire queue will be rendered client side, added a bunch
of different information outputs for the reports queue such as report
counts, panel data output blah blah blah

### CODE REVIEW

**Comment by RePod** [comment]
Regist status? Is this based on old, master, or #220?

If it's based on old, rejected. If it's based on master, I'll work on it/#220 after merging.

#220 is tentative as-is but most of its final needs revolve around Admin anyway (specifically Admin supporting multiple files or a dedicated file table).

**Comment by Apogate** [comment]
Regist isn't included in this PR. I'll fight that battle another day

**Comment by RePod** [comment]
Was the report table changed?

**Comment by Apogate** [comment]
Report table was mothballed, we are transitioning to one rendered client-side with js. Much less resource intensive, and makes it much easier to manipulate data. 

This PR has all the hooks for that, we just lack the actual js to display it.

**Comment by RePod** [comment]
I meant SQL table.

**Comment by RePod** [comment]
Also consider implementing something similar to what I did in #220 to [swap out parts of the Admin interface](https://github.com/spootTheLousy/saguaro/blob/544c458799b21af7002e39115dd86389685e821a/_core/admin/tables.php#L177).

Main benefit of this is besides being able to tailor to specific use cases (for instance, I added Modern to support multiple files), we can also tailor to specific access levels.

Only drawback is maintaining consistency among them.
A template system wouldn't be the best solution but it's not off the table.

**Comment by Apogate** [comment]
> sql reports table changed

yes it was. I've also tried to remove references to hardcoded "reports" table name, replacing it with `SQLREPORTS` constant

**Comment by RePod** [comment]
Then where are reports being stored?

**Comment by Apogate** [comment]
still in a table. I'm just making the table name configurable instead of hardcoded

**Comment by Apogate** [comment]
out of date

**Pull request closed without merging**
